e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL,
#                       document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls.conf import path
from .views import (
    HomeView, ItemDetailView, add_coupon_view,
    add_item_to_cart, remove_from_cart, remove_single_item_from_cart,
    add_single_item_to_cart, remove_item_from_cart,
    OrderSummaryView, CheckoutView, PaymentView, CreatePayment,
)

app_name = 'store'

urlpatterns = [
    path(route='', view=HomeView.as_view(), name='home'),
    path(route='product/<slug>', view=ItemDetailView.as_view(), name='product'),
    path(route='order-summary/',
         view=OrderSummaryView.as_view(), name='order-summary'),
    path(route='checkout/',
         view=CheckoutView.as_view(), name='checkout'),
    path(route='payment/<payment_option>',
         view=PaymentView.as_view(), name='payment'),
    path(route='stripe-payment',
         view=CreatePayment.as_view(), name='stripe-payment'),
    path(route='add_item_to_cart/<slug>',
         view=add_item_to_cart, name='add-item-to-cart'),
    path(route='remove_from_cart/<slug>',
         view=remove_from_cart, name='remove-from-cart'),
    path(route='remove-single-item-from-cart/<slug>',
         view=remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path(route='add-single-item-to-cart/<slug>',
         view=add_single_item_to_cart, name='add-single-item-to-cart'),
    path(route='remove-item-from-cart/<slug>',
         view=remove_item_from_cart, name='remove-item-from-cart'),
    path(route='add-coupon', view=add_coupon_view, name='add-coupon')
]

store/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Item(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=100)
    image = models.ImageField(default='default.jpg')
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(
        choices=CATEGORY_CHOICES, max_length=2, default='S')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    description = models.TextField(default=f'Description of {title}')

    def get_absolute_url(self):
        return reverse('store:product', kwargs={'slug': self.slug})

    def get_final_price(self):
        if self.discount_price:
            return self.discount_price
        else:
            return self.price

    def get_add_item_to_cart_url(self):
        return reverse('store:add-item-to-cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('store:remove-from-cart', kwargs={'slug': self.slug})

    def __str__(self) -> str:
        return self.title


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(to=Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.quantity} of {self.item.title}'

    def get_total_price(self):
        if self.item.discount_price:
            return self.item.discount_price * self.quantity
        else:
            return self.item.price * self.quantity


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_accepted = models.BooleanField(default=False)

    def total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_price()
        if self.coupon:
            discount = self.coupon.discount_amount
            total = total * (1 - discount)
        return total

    def amount_save(self):
        if self.coupon:
            total = 0
            for order_item in self.items.all():
                total += order_item.get_total_price()
            discount = self.coupon.discount_amount
            return total * discount

    def __str__(self):
        return self.user.email


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    code = models.CharField(max_length=50)
    amount = models.FloatField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.amount)


class Coupon(models.Model):
    code = models.CharField(max_length=30)
    discount_amount = models.FloatField()

    def __str__(self) -> str:
        return self.code

templates/shop/footer.html
<!--Footer-->
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/shop/home.html
{% extends 'shop/base.html' %}

{% block extra_head %}
<style type="text/css">
  html,
  body,
  header,
  .carousel {
    height: 60vh;
  }

  @media (max-width: 740px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }

  @media (min-width: 800px) and (max-width: 850px) {

    html,
    body,
    header,
    .carousel {
      height: 100vh;
    }
  }
</style>
{% endblock extra_head %}

{% block content %}
<main>
  <div class="container">
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in items %}
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card">

            <!--Card image-->
            <div class="view overlay">
              <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                alt="">
              <a>
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="{{ item.get_absolute_url }}" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>{{ item.price }}</strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        {% endfor %}

      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}



        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active">
          <a class="page-link" href="#">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}
          </a>
          </li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
      </ul>
    </nav>
    <!--Pagination-->
    {% endif %}

  </div>
</main>
{% endblock content %}

templates/shop/nav.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'store:home' %}">
            <strong class="blue-text">E-commerce</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link waves-effect" href="{% url 'store:home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'store:checkout' %}">Checkout</a>
                </li>
                {% endif %}
            </ul>


            <!-- Right -->
            <ul class="navbar-nav nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link waves-effect" href="{% url 'store:order-summary' %}">
                        <span class="badge red z-depth-1 mr-1"> {{ request.user | cart_items_count }} </span>
                        <i class="fas fa-shopping-cart"></i>
                        <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_logout' %}" class="nav-link border border-light rounded waves-effect">
                        Logout
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'account_login' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Login </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'account_signup' %}" class="nav-link waves-effect">
                        <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                    </a>
                </li>
                {% endif %}
            </ul>



        </div>

    </div>
</nav>
<!-- Navbar -->

templates/shop/order_summary.html
{% extends 'shop/base.html' %}

{% block extra_head %}
<style type="text/css">
    html,
    body,
    header,
    .carousel {
        height: 60vh;
    }

    @media (max-width: 740px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
    }

    @media (min-width: 800px) and (max-width: 850px) {

        html,
        body,
        header,
        .carousel {
            height: 100vh;
        }
    }
</style>
{% endblock extra_head %}

{% block content %}
<main>
    <div class="container">

        <!--Section: Products v.3-->
        <section class="mb-4">

            <!--Grid row-->
            <div class="row wow fadeIn">
                <h2>Order summmary</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Price</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Total price</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order_item in order.items.all %}

                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.item.title }}</td>
                            <td>{{ order_item.item.get_final_price | floatformat:2 }}</td>
                            <td>
                                <a href="{% url 'store:remove-single-item-from-cart' slug=order_item.item.slug %}"
                                    class="fas fa-minus mr-2"></a>
                                {{ order_item.quantity }}
                                <a href="{% url 'store:add-single-item-to-cart' slug=order_item.item.slug %}"
                                    class="fas fa-plus ml-2"></a>
                            </td>
                            <td>
                                ${{ order_item.get_total_price | floatformat:2 }}
                                <a href="{% url 'store:remove-item-from-cart' slug=order_item.item.slug %}"
                                    class="fas fa-trash float-right"></a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan='5'>Your cart is empty</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
                            </td>
                        </tr>

                        {% endfor %}
                        {% if order.total %}
                        <tr>
                            <td colspan="4">Order total price</td>
                            <td>${{ order.total | floatformat:2 }}</td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right" href="{% url 'store:home' %}">Continue
                                    shopping</a>
                                <a class="btn btn-warning float-right" href="{% url 'store:checkout' %}">Proceed to
                                    checkout</a>
                            </td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>

            </div>

        </section>
    </div>
</main>
{% endblock content %}

templates/shop/payment.html
{% extends 'shop/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
<style>
    input {
        border-radius: 6px;
        margin-bottom: 6px;
        padding: 12px;
        border: 1px solid rgba(50, 50, 93, 0.1);
        height: 44px;
        font-size: 16px;
        width: 100%;
        background: white;
    }

    .result-message {
        line-height: 22px;
        font-size: 16px;
    }

    .result-message a {
        color: rgb(89, 111, 214);
        font-weight: 600;
        text-decoration: none;
    }

    .hidden {
        display: none;
    }

    #card-error {
        color: rgb(105, 115, 134);
        text-align: left;
        font-size: 13px;
        line-height: 17px;
        margin-top: 12px;
    }

    #card-element {
        border-radius: 4px 4px 0 0;
        padding: 12px;
        border: 1px solid rgba(50, 50, 93, 0.1);
        height: 44px;
        width: 100%;
        background: white;
    }

    #payment-request-button {
        margin-bottom: 32px;
    }

    button:hover {
        filter: contrast(115%);
    }

    button:disabled {
        opacity: 0.5;
        cursor: default;
    }

    /* spinner/processing state, errors */
    .spinner,
    .spinner:before,
    .spinner:after {
        border-radius: 50%;
    }

    .spinner {
        color: #ffffff;
        font-size: 22px;
        text-indent: -99999px;
        margin: 0px auto;
        position: relative;
        width: 20px;
        height: 20px;
        box-shadow: inset 0 0 0 2px;
        -webkit-transform: translateZ(0);
        -ms-transform: translateZ(0);
        transform: translateZ(0);
    }

    .spinner:before,
    .spinner:after {
        position: absolute;
        content: "";
    }

    .spinner:before {
        width: 10.4px;
        height: 20.4px;
        background: #5469d4;
        border-radius: 20.4px 0 0 20.4px;
        top: -0.2px;
        left: -0.2px;
        -webkit-transform-origin: 10.4px 10.2px;
        transform-origin: 10.4px 10.2px;
        -webkit-animation: loading 2s infinite ease 1.5s;
        animation: loading 2s infinite ease 1.5s;
    }

    .spinner:after {
        width: 10.4px;
        height: 10.2px;
        background: #5469d4;
        border-radius: 0 10.2px 10.2px 0;
        top: -0.1px;
        left: 10.2px;
        -webkit-transform-origin: 0px 10.2px;
        transform-origin: 0px 10.2px;
        -webkit-animation: loading 2s infinite ease;
        animation: loading 2s infinite ease;
    }

    @-webkit-keyframes loading {
        0% {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @keyframes loading {
        0% {
            -webkit-transform: rotate(0deg);
            transform: rotate(0deg);
        }

        100% {
            -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
        }
    }

    @media only screen and (max-width: 600px) {
        form {
            width: 80vw;
        }
    }
</style>
<script src="https://js.stripe.com/v3/"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
{% endblock %}

{% block content %}
<!--Main layout-->
<main>
    <div class="container wow fadeIn">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Payment</h2>

        <!--Grid row-->
        <div class="row">

            <!--Grid column-->
            <div class="col-md-10 offset-1 mb-4">

                <!--Card-->
                <div class="card pl-3 pr-3 pt-3">
                    <form id="payment-form">
                        <div id="card-element">
                            <!--Stripe.js injects the Card Element-->
                        </div>
                        <button class="btn btn-primary float-right" id="submit">
                            <div class="spinner hidden" id="spinner"></div>
                            <span id="button-text">Pay now</span>
                        </button>
                        <p id="card-error" role="alert"></p>
                        <p class="result-message hidden">
                            Payment succeeded, continue shopping
                            <a href="" target="_blank">shopping.</a>
                        </p>
                    </form>
                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->

            <div class="col-md-10 offset-1">
                {% include 'shop/sidebar.html' %}
            </div>

        </div>
        <!--Grid row-->
</main>
<!--Main layout-->
{% endblock content %}

{% block extra_body %}
{% csrf_token %}
<script>
    // A reference to Stripe.js initialized with a fake API key.
    // Sign in to see examples pre-filled with your key.
    var stripe = Stripe("pk_test_51IlOonFzjY46dDwnrlkqCW5MLzbpovWnM3XyjnbIvZLQiPzNJsUgrYMcuAHU9Y904w6a001SEB1dzobCQrlcE9Ce00n62v6oN2");

    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    // Disable the button until we have Stripe set up on the page
    document.querySelector("button").disabled = true;
    fetch("{% url 'store:stripe-payment' %}", {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            'X-CSRFToken': csrftoken,
        },
    })
        .then(function (result) {
            return result.json();
        })
        .then(function (data) {
            var elements = stripe.elements();

            var style = {
                base: {
                    color: "#32325d",
                    fontFamily: 'Arial, sans-serif',
                    fontSmoothing: "antialiased",
                    fontSize: "16px",
                    "::placeholder": {
                        color: "#32325d"
                    }
                },
                invalid: {
                    fontFamily: 'Arial, sans-serif',
                    color: "#fa755a",
                    iconColor: "#fa755a"
                }
            };

            var card = elements.create("card", { style: style });
            // Stripe injects an iframe into the DOM
            card.mount("#card-element");

            card.on("change", function (event) {
                // Disable the Pay button if there are no card details in the Element
                document.querySelector("button").disabled = event.empty;
                document.querySelector("#card-error").textContent = event.error ? event.error.message : "";
            });

            var form = document.getElementById("payment-form");
            form.addEventListener("submit", function (event) {
                event.preventDefault();
                console.log("data", data)
                // Complete payment when the submit button is clicked
                payWithCard(stripe, card, data.clientSecret);
            });
        });

    // Calls stripe.confirmCardPayment
    // If the card requires authentication Stripe shows a pop-up modal to
    // prompt the user to enter authentication details without leaving your page.
    var payWithCard = function (stripe, card, clientSecret) {
        loading(true);
        stripe
            .confirmCardPayment(clientSecret, {
                payment_method: {
                    card: card
                }
            })
            .then(function (result) {
                if (result.error) {
                    // Show error to your customer
                    showError(result.error.message);
                } else {
                    // The payment succeeded!
                    orderComplete(result.paymentIntent.id);
                }
            });
    };

    /* ------- UI helpers ------- */

    // Shows a success message when the payment is complete
    var orderComplete = function (paymentIntentId) {
        loading(false);
        document
            .querySelector(".result-message a")
            .setAttribute(
                "href",
                "/"
            );
        document.querySelector(".result-message").classList.remove("hidden");
        document.querySelector("button").disabled = true;
    };

    // Show the customer the error from Stripe if their card fails to charge
    var showError = function (errorMsgText) {
        loading(false);
        var errorMsg = document.querySelector("#card-error");
        errorMsg.textContent = errorMsgText;
        setTimeout(function () {
            errorMsg.textContent = "";
        }, 4000);
    };

    // Show a spinner on payment submission
    var loading = function (isLoading) {
        if (isLoading) {
            // Disable the button and show a spinner
            document.querySelector("button").disabled = true;
            document.querySelector("#spinner").classList.remove("hidden");
            document.querySelector("#button-text").classList.add("hidden");
        } else {
            document.querySelector("button").disabled = false;
            document.querySelector("#spinner").classList.add("hidden");
            document.querySelector("#button-text").classList.remove("hidden");
        }
    };
</script>
{% endblock extra_body %}

templates/shop/product.html
{% extends 'shop/base.html' %}

{% block content %}
<main>
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{ item.get_category_display }}</span>
            </a>
            <a href="">
              <span class="badge blue mr-1">New</span>
            </a>
            <a href="">
              <span class="badge red mr-1">Bestseller</span>
            </a>
          </div>

          <p class="lead">
            {% if item.discount_price %}
            <span class="mr-1">
              <del>${{ item.price }}</del>
            </span>
            {% endif %}
            <span>${{ item.get_final_price }}</span>
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
            sint voluptatibus!
            Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>

          <form class="d-flex justify-content-left">
            <!-- Default input -->
            <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
            <a href='{{ item.get_add_item_to_cart_url }}' class="btn btn-primary btn-md my-0 p" type="submit">Add to
              cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href='{{ item.get_remove_from_cart_url }}' class="btn btn-danger btn-md my-0 p" type="submit">Remove
            </a>

          </form>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
{% endblock content %}

templates/shop/scripts.html
{% load static %}
<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();

</script>